package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chapter generated by hbm2java
 */
@Entity
@Table(name = "chapter", catalog = "jwat_v2")
public class Chapter implements java.io.Serializable {

	private int id;
	private Classes classes;
	private String name;
	private Set<MainSchedules> mainScheduleses = new HashSet<MainSchedules>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public Chapter() {
	}

	public Chapter(int id) {
		this.id = id;
	}

	public Chapter(int id, Classes classes, String name, Set<MainSchedules> mainScheduleses, Set<Users> userses) {
		this.id = id;
		this.classes = classes;
		this.name = name;
		this.mainScheduleses = mainScheduleses;
		this.userses = userses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chapter")
	public Set<MainSchedules> getMainScheduleses() {
		return this.mainScheduleses;
	}

	public void setMainScheduleses(Set<MainSchedules> mainScheduleses) {
		this.mainScheduleses = mainScheduleses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "process", catalog = "jwat_v2", joinColumns = {
			@JoinColumn(name = "chapter_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
