package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MainSchedules generated by hbm2java
 */
@Entity
@Table(name = "main_schedules", catalog = "jwat_v2")
public class MainSchedules implements java.io.Serializable {

	private int id;
	private Chapter chapter;
	private Rooms rooms;
	private String trainerName;
	private Integer year;
	private Integer week;
	private Integer weekday;
	private Boolean period;
	private Date startTime;
	private Date endTime;
	private String note;
	private Set<RollCalls> rollCallses = new HashSet<RollCalls>(0);

	public MainSchedules() {
	}

	public MainSchedules(int id) {
		this.id = id;
	}

	public MainSchedules(int id, Chapter chapter, Rooms rooms, String trainerName, Integer year, Integer week,
			Integer weekday, Boolean period, Date startTime, Date endTime, String note, Set<RollCalls> rollCallses) {
		this.id = id;
		this.chapter = chapter;
		this.rooms = rooms;
		this.trainerName = trainerName;
		this.year = year;
		this.week = week;
		this.weekday = weekday;
		this.period = period;
		this.startTime = startTime;
		this.endTime = endTime;
		this.note = note;
		this.rollCallses = rollCallses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chapter_id")
	public Chapter getChapter() {
		return this.chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id")
	public Rooms getRooms() {
		return this.rooms;
	}

	public void setRooms(Rooms rooms) {
		this.rooms = rooms;
	}

	@Column(name = "trainer_name", length = 100)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "week")
	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	@Column(name = "weekday")
	public Integer getWeekday() {
		return this.weekday;
	}

	public void setWeekday(Integer weekday) {
		this.weekday = weekday;
	}

	@Column(name = "period")
	public Boolean getPeriod() {
		return this.period;
	}

	public void setPeriod(Boolean period) {
		this.period = period;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_time", length = 10)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_time", length = 10)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mainSchedules")
	public Set<RollCalls> getRollCallses() {
		return this.rollCallses;
	}

	public void setRollCallses(Set<RollCalls> rollCallses) {
		this.rollCallses = rollCallses;
	}

}
