package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notifications generated by hbm2java
 */
@Entity
@Table(name = "notifications", catalog = "jwat_v2")
public class Notifications implements java.io.Serializable {

	private int id;
	private String title;
	private String content;
	private String listenerList;
	private Boolean status;
	private Date dueDate;
	private Boolean isRegis;
	private Integer year;
	private Integer week;
	private Date updatedAt;
	private Date createdAt;
	private Set<UserSeenNotification> userSeenNotifications = new HashSet<UserSeenNotification>(0);

	public Notifications() {
	}

	public Notifications(int id) {
		this.id = id;
	}

	public Notifications(int id, String title, String content, String listenerList, Boolean status, Date dueDate,
			Boolean isRegis, Integer year, Integer week, Date updatedAt, Date createdAt,
			Set<UserSeenNotification> userSeenNotifications) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.listenerList = listenerList;
		this.status = status;
		this.dueDate = dueDate;
		this.isRegis = isRegis;
		this.year = year;
		this.week = week;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
		this.userSeenNotifications = userSeenNotifications;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "listener_list", length = 65535)
	public String getListenerList() {
		return this.listenerList;
	}

	public void setListenerList(String listenerList) {
		this.listenerList = listenerList;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "is_regis")
	public Boolean getIsRegis() {
		return this.isRegis;
	}

	public void setIsRegis(Boolean isRegis) {
		this.isRegis = isRegis;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "week")
	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notifications")
	public Set<UserSeenNotification> getUserSeenNotifications() {
		return this.userSeenNotifications;
	}

	public void setUserSeenNotifications(Set<UserSeenNotification> userSeenNotifications) {
		this.userSeenNotifications = userSeenNotifications;
	}

}
