package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RollCalls generated by hbm2java
 */
@Entity
@Table(name = "roll_calls", catalog = "jwat_v2")
public class RollCalls implements java.io.Serializable {

	private RollCallsId id;
	private MainSchedules mainSchedules;
	private Users users;
	private Date rollCallAt;

	public RollCalls() {
	}

	public RollCalls(RollCallsId id, MainSchedules mainSchedules, Users users) {
		this.id = id;
		this.mainSchedules = mainSchedules;
		this.users = users;
	}

	public RollCalls(RollCallsId id, MainSchedules mainSchedules, Users users, Date rollCallAt) {
		this.id = id;
		this.mainSchedules = mainSchedules;
		this.users = users;
		this.rollCallAt = rollCallAt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mainScheduleId", column = @Column(name = "main_schedule_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public RollCallsId getId() {
		return this.id;
	}

	public void setId(RollCallsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "main_schedule_id", nullable = false, insertable = false, updatable = false)
	public MainSchedules getMainSchedules() {
		return this.mainSchedules;
	}

	public void setMainSchedules(MainSchedules mainSchedules) {
		this.mainSchedules = mainSchedules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "roll_call_at", length = 10)
	public Date getRollCallAt() {
		return this.rollCallAt;
	}

	public void setRollCallAt(Date rollCallAt) {
		this.rollCallAt = rollCallAt;
	}

}
