package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RollCallsId generated by hbm2java
 */
@Embeddable
public class RollCallsId implements java.io.Serializable {

	private int mainScheduleId;
	private int userId;

	public RollCallsId() {
	}

	public RollCallsId(int mainScheduleId, int userId) {
		this.mainScheduleId = mainScheduleId;
		this.userId = userId;
	}

	@Column(name = "main_schedule_id", nullable = false)
	public int getMainScheduleId() {
		return this.mainScheduleId;
	}

	public void setMainScheduleId(int mainScheduleId) {
		this.mainScheduleId = mainScheduleId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RollCallsId))
			return false;
		RollCallsId castOther = (RollCallsId) other;

		return (this.getMainScheduleId() == castOther.getMainScheduleId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMainScheduleId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
