package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rooms generated by hbm2java
 */
@Entity
@Table(name = "rooms", catalog = "jwat_v2")
public class Rooms implements java.io.Serializable {

	private int id;
	private String name;
	private Integer maximumSeat;
	private String description;
	private String note;
	private Set<MainSchedules> mainScheduleses = new HashSet<MainSchedules>(0);

	public Rooms() {
	}

	public Rooms(int id) {
		this.id = id;
	}

	public Rooms(int id, String name, Integer maximumSeat, String description, String note,
			Set<MainSchedules> mainScheduleses) {
		this.id = id;
		this.name = name;
		this.maximumSeat = maximumSeat;
		this.description = description;
		this.note = note;
		this.mainScheduleses = mainScheduleses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "maximum_seat")
	public Integer getMaximumSeat() {
		return this.maximumSeat;
	}

	public void setMaximumSeat(Integer maximumSeat) {
		this.maximumSeat = maximumSeat;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rooms")
	public Set<MainSchedules> getMainScheduleses() {
		return this.mainScheduleses;
	}

	public void setMainScheduleses(Set<MainSchedules> mainScheduleses) {
		this.mainScheduleses = mainScheduleses;
	}

}
