package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentRegisterSchedule generated by hbm2java
 */
@Entity
@Table(name = "student_register_schedule", catalog = "jwat_v2")
public class StudentRegisterSchedule implements java.io.Serializable {

	private int id;
	private Users users;
	private Integer year;
	private Integer week;
	private Integer weekday;
	private Boolean period;

	public StudentRegisterSchedule() {
	}

	public StudentRegisterSchedule(int id) {
		this.id = id;
	}

	public StudentRegisterSchedule(int id, Users users, Integer year, Integer week, Integer weekday, Boolean period) {
		this.id = id;
		this.users = users;
		this.year = year;
		this.week = week;
		this.weekday = weekday;
		this.period = period;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "week")
	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	@Column(name = "weekday")
	public Integer getWeekday() {
		return this.weekday;
	}

	public void setWeekday(Integer weekday) {
		this.weekday = weekday;
	}

	@Column(name = "period")
	public Boolean getPeriod() {
		return this.period;
	}

	public void setPeriod(Boolean period) {
		this.period = period;
	}

}
