package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSeenNotification generated by hbm2java
 */
@Entity
@Table(name = "user_seen_notification", catalog = "jwat_v2")
public class UserSeenNotification implements java.io.Serializable {

	private UserSeenNotificationId id;
	private Notifications notifications;
	private Users users;
	private Boolean seenStatus;
	private Date seenAt;

	public UserSeenNotification() {
	}

	public UserSeenNotification(UserSeenNotificationId id, Notifications notifications, Users users) {
		this.id = id;
		this.notifications = notifications;
		this.users = users;
	}

	public UserSeenNotification(UserSeenNotificationId id, Notifications notifications, Users users, Boolean seenStatus,
			Date seenAt) {
		this.id = id;
		this.notifications = notifications;
		this.users = users;
		this.seenStatus = seenStatus;
		this.seenAt = seenAt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "notificationId", column = @Column(name = "notification_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public UserSeenNotificationId getId() {
		return this.id;
	}

	public void setId(UserSeenNotificationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notification_id", nullable = false, insertable = false, updatable = false)
	public Notifications getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Notifications notifications) {
		this.notifications = notifications;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "seen_status")
	public Boolean getSeenStatus() {
		return this.seenStatus;
	}

	public void setSeenStatus(Boolean seenStatus) {
		this.seenStatus = seenStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "seen_at", length = 19)
	public Date getSeenAt() {
		return this.seenAt;
	}

	public void setSeenAt(Date seenAt) {
		this.seenAt = seenAt;
	}

}
