package entity;
// Generated Feb 20, 2020, 1:47:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserSeenNotificationId generated by hbm2java
 */
@Embeddable
public class UserSeenNotificationId implements java.io.Serializable {

	private int notificationId;
	private int userId;

	public UserSeenNotificationId() {
	}

	public UserSeenNotificationId(int notificationId, int userId) {
		this.notificationId = notificationId;
		this.userId = userId;
	}

	@Column(name = "notification_id", nullable = false)
	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserSeenNotificationId))
			return false;
		UserSeenNotificationId castOther = (UserSeenNotificationId) other;

		return (this.getNotificationId() == castOther.getNotificationId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNotificationId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
